version: '3'

services:
  db:
    image: postgres
    networks:
      - pyconark
    volumes:
        - .:/dbdata
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    networks:
      - pyconark
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  pyconark:


