version: "3.3"

services:
  db:
    image: postgres
    networks:
      - pyconark
    volumes:
      - type: volume
        source: dbdata
        target: /data/db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    networks:
      - pyconark
    ports:
      - "80:8000"
    depends_on:
      - db

networks:
  pyconark:

volumes:
  dbdata:
